version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build: ./blog_be
    container_name: spring_boot_container
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      IMAGE_BASE_UPLOAD_DIR: /home/jumbochips/project/blog/uploads

    ports:
      - "8080:8080"
    networks:
      - app_network
    volumes:
      - /home/jumbochips/project/blog/uploads:/home/jumbochips/project/blog/uploads

  frontend:
    build: ./blog_fe
    container_name: nuxt_container
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      API_BASE_URL: "https://jumbochips.com/api/v1"  # API 백엔드 URL 설정
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
