version: '3.8'
services:
  db:
    image: mysql:8.0.41
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0409
      MYSQL_DATABASE: blog
      MYSQL_USER: jumbochips
      MYSQL_PASSWORD: 0409
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
